# Generated by Django 3.2.5 on 2021-12-30 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WomenSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tops', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('EXTRA_LARGE', 'Extra-Large')], max_length=100)),
                ('bottoms', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('EXTRA_LARGE', 'Extra-Large')], max_length=100)),
                ('footwear', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('EXTRA_LARGE', 'Extra-Large')], max_length=100)),
                ('bra', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('EXTRA_LARGE', 'Extra-Large')], max_length=100)),
                ('initial_profile_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_information.initialprofiledetail')),
            ],
        ),
        migrations.CreateModel(
            name='StyleProfileWomen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feminine_shape', models.CharField(choices=[('DIAMOND', 'Diamond'), ('INVERTED_TRIANGLE', 'Inverted-Triangle'), ('RECTANGLE', 'Rectangle'), ('OVAL', 'Oval'), ('Trianlge', 'Trianlge'), ('HOUR_GLASS', 'Hour-Glass')], max_length=100)),
                ('top_style', models.CharField(choices=[('FITTED', 'Fitted'), ('STRAIGHT', 'Straight'), ('LOOSE', 'Loose')], max_length=100)),
                ('bottom_style', models.CharField(choices=[('FITTED', 'Fitted'), ('STRAIGHT', 'Straight'), ('LOOSE', 'Loose')], max_length=100)),
                ('heel_height', models.CharField(choices=[('FLAT', 'Flat'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'HIGH')], max_length=100)),
                ('shoe_style', models.CharField(choices=[('FLAT_SHOES', 'Flat-Shoes'), ('HEELED_SHOES', 'Heeled-Shoes'), ('SANDALS', 'Sandals'), ('SNEAKERS', 'Sneakers'), ('BOOTS', 'Boots'), ('HEELED_BOOTS', 'Heeled-Boots')], max_length=100)),
                ('casual_preference', models.CharField(choices=[('FEMININE', 'Feminine'), ('EDGY', 'Edgy'), ('CASUAL', 'Casual'), ('SMART_CASUAL', 'Smart-Casual')], max_length=100)),
                ('work_preference', models.CharField(choices=[('CASUAL', 'Casual'), ('SMART_CASUAL', 'Smart-Casual'), ('BUSINESS_CASUAL', 'Business-Casual'), ('BUSINESS', 'Business')], max_length=100)),
                ('prints', models.CharField(choices=[('LARGE_PRINTS', 'Large-Prints'), ('GEOMETRIC_PRINTS', 'Geometric-Prints'), ('FLORAL_PRINTS', 'Floral-Prints'), ('ANIMAL_PRINTS', 'Animal-Prints')], max_length=100)),
                ('colors', models.CharField(choices=[('BLACK', 'Black'), ('BLUE', 'Blue'), ('BROWN', 'Brown'), ('GREY', 'Grey'), ('KHAKI', 'Khaki'), ('LIGHT_BLUE', 'Light-Blue'), ('NAVY', 'Navy'), ('OLIVE', 'Olive'), ('PINK', 'Pink'), ('PURPLE', 'Purple'), ('RED', 'Red'), ('GREEN', 'Green'), ('SALMON', 'Salmon'), ('WHITE', 'White'), ('YELLOW', 'Yellow')], max_length=100)),
                ('feedback', models.CharField(max_length=500)),
                ('image1', models.ImageField(blank=True, upload_to='pictures')),
                ('insta_link', models.URLField(blank=True)),
                ('extra_tailored_sizes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_information.extratailoredsize')),
                ('men_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='women.womensize')),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_information.personalinfo')),
                ('shoe_characterics', models.ManyToManyField(to='general_information.ShoeCharacteristic')),
            ],
        ),
    ]
