# Generated by Django 3.2.5 on 2021-12-29 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InitialProfileDetails',
            new_name='InitialProfileDetail',
        ),
        migrations.CreateModel(
            name='MenSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tops', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('EXTRA_LARGE', 'Extra-Large')], max_length=100)),
                ('bottoms', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('EXTRA_LARGE', 'Extra-Large')], max_length=100)),
                ('footwear', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('EXTRA_LARGE', 'Extra-Large')], max_length=100)),
                ('blazer', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('EXTRA_LARGE', 'Extra-Large')], max_length=100)),
                ('formal', models.CharField(blank=True, choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('EXTRA_LARGE', 'Extra-Large')], max_length=100)),
                ('initial_profile_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='men.initialprofiledetail')),
            ],
        ),
    ]
