# Generated by Django 3.2.5 on 2021-12-29 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0003_extratailoredsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charateristic', models.CharField(choices=[('COMFORT', 'Comfort'), ('STYLE', 'Style'), ('Quality', 'Quality')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StyleProfileMen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_preferrence', models.CharField(choices=[('CASUAL', 'Casual'), ('SMART_CASUAL', 'Smart-Casual'), ('BUSINESS_CASUAL', 'Business-Casual'), ('BUSINESS', 'Business')], max_length=100)),
                ('casual_preferrence', models.CharField(choices=[('CASUAL_CHIC', 'Casual-Chic'), ('EDGY', 'Edgy'), ('CASUAL', 'Casual'), ('SMART_CASUAL', 'Smart-Casual')], max_length=100)),
                ('topfit', models.CharField(choices=[('REGULAR', 'Regular'), ('SLIM', 'Slim')], max_length=100)),
                ('bottomfit', models.CharField(choices=[('SKINNY', 'Skinny'), ('SLIM', 'Slim'), ('NORMAL', 'Normal'), ('LOOSE', 'Loose'), ('TAPERED', 'Tapered')], max_length=100)),
                ('shoe_type', models.CharField(choices=[('LOAFERS', 'Loafers'), ('LEATHER_SNEAKERS', 'Leather-Sneakers'), ('DRESS_SHOES', 'Dress-Shoes'), ('HI_TOP_SNEAKERS', 'Hi-Top-Sneakers'), ('CHELSEA_BOOTS', 'Chelsea-Boots'), ('BOOTS', 'BOOTS')], max_length=100)),
                ('no_nos', models.CharField(choices=[('LARGE_PRINTS', 'Large-Prints'), ('SHORTS', 'Shorts'), ('COLORED_TROUSERS', 'Colored-Trousers'), ('SHIRTS', 'Shirts'), ('POLO_SHIRTS', 'Polo-Shirts'), ('PLAID_SHIRTS', 'Plaid-Shirts')], max_length=100)),
                ('colors', models.CharField(choices=[('BLACK', 'Black'), ('BLUE', 'Blue'), ('BROWN', 'Brown'), ('GREY', 'Grey'), ('KHAKI', 'Khaki'), ('LIGHT_BLUE', 'Light-Blue'), ('NAVY', 'Navy'), ('OLIVE', 'Olive'), ('PINK', 'Pink'), ('PURPLE', 'Purple'), ('RED', 'Red'), ('GREEN', 'Green'), ('SALMON', 'Salmon'), ('WHITE', 'White'), ('YELLOW', 'Yellow')], max_length=100)),
                ('feedback', models.CharField(max_length=500)),
                ('image1', models.ImageField(blank=True, upload_to='')),
                ('insta_link', models.URLField(blank=True)),
                ('men_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='men.mensize')),
                ('shoe_characterics', models.ManyToManyField(to='men.ShoeCharacteristic')),
            ],
        ),
    ]
