# Generated by Django 3.2.5 on 2021-12-30 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=999, max_digits=999)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], max_length=20)),
                ('payment_method', models.CharField(choices=[('Credit_CARD', 'Credit-Card'), ('PAYPAL', 'Paypal'), ('MASTER_CARD', 'Master-Card')], max_length=20)),
                ('request_date', models.DateField()),
                ('receiving_city', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('arrival_date', models.DateField()),
                ('flight_booked', models.BooleanField(default=False)),
                ('flight_number', models.CharField(max_length=100)),
                ('date_to_receive', models.DateField()),
                ('time_to_receive', models.TimeField()),
                ('address', models.CharField(max_length=500)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'men'), ('model', 'styleprofilemen')), models.Q(('app_label', 'women'), ('model', 'styleprofilewomen')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocaasion', models.CharField(max_length=500)),
                ('spending_on_clothing', models.CharField(choices=[('RANGE1', '40-80'), ('RANGE2', '80-150'), ('RANGE3', '150-300'), ('RANGE4', '300-500'), ('RANGE5', '500-open end'), ('RANGE6', 'Female')], max_length=50)),
                ('spending_on_shoes', models.CharField(choices=[('RANGE1', '40-80'), ('RANGE2', '80-150'), ('RANGE3', '150-300'), ('RANGE4', '300-500'), ('RANGE5', '500-open end'), ('RANGE6', 'Female')], max_length=50)),
                ('spending_on_bag', models.CharField(choices=[('RANGE1', '40-80'), ('RANGE2', '80-150'), ('RANGE3', '150-300'), ('RANGE4', '300-500'), ('RANGE5', '500-open end'), ('RANGE6', 'Female')], max_length=50)),
                ('pic', models.ImageField(blank=True, upload_to='')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_on', models.CharField(choices=[('ADD_ON1', 'Add-on1'), ('ADD_IN2', 'Add-on2')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('delivery_address', models.CharField(max_length=500)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
