# Generated by Django 3.2.5 on 2021-12-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='budget',
            field=models.DecimalField(decimal_places=5, max_digits=999),
        ),
    ]
